'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let items=[],ids=[],state={answers:{},notes:{},overall:'',name:''},page=0,key=''; const size=12;
function verdict(id){let v=state.answers[id]||'-';return (state.notes[id]||'').trim()&&v!=='X'?'F':v}
function encode(){return ids.map(verdict).join('')}
function save(){try{localStorage.setItem(key,JSON.stringify(state));history.replaceState(null,'','#r='+encode())}catch(e){$('#status').textContent='Browser saving unavailable. Use Copy answers.'}}
function selected(){return items.filter(i=>(!$('#brand').value||i.brand===$('#brand').value)&&(!$('#batch').value||i.batch==='2026-09-12'))}
function media(v){if(v.video)return '<video controls playsinline preload="none" poster="'+esc(v.poster||'')+'" style="--ratio:'+v.width+'/'+v.height+'" aria-label="Reel '+esc(v.id)+'"><source src="'+esc(v.video)+'" type="video/mp4"></video>';if(v.image)return '<a href="'+esc(v.image)+'" target="_blank" rel="noopener"><img loading="lazy" src="'+esc(v.image)+'" width="'+v.width+'" height="'+v.height+'" alt="'+esc(v.label||v.id)+'"></a>';return '<div class="empty">Video unavailable</div>'}
function render(){let list=selected();page=Math.min(page,Math.max(0,Math.ceil(list.length/size)-1));$('#items').innerHTML=list.slice(page*size,(page+1)*size).map(i=>'<article class="item"><div class="number"><span>'+esc(i.code)+'</span><span>'+esc(i.brand||'')+'</span></div><div class="variants" style="--cols:'+i.variants.length+'">'+i.variants.map(v=>'<div class="variant">'+media(v)+(v.label?'<div class="label">'+esc(v.label)+'</div>':'')+(v.reference?'':'<div class="controls" data-id="'+esc(v.id)+'">'+[['K','Keep'],['F','Flag'],['X','Kill']].map(([k,t])=>'<button aria-pressed="'+(verdict(v.id)===k)+'" data-verdict="'+k+'">'+t+'</button>').join('')+'</div><textarea class="'+((state.notes[v.id]||'').trim()?'has-note':'')+'" data-note="'+esc(v.id)+'" aria-label="Notes for '+esc(i.code)+'" placeholder="Notes">'+esc(state.notes[v.id]||'')+'</textarea>')+'<div class="source">'+(v.source?'<a href="'+esc(v.source)+'" target="_blank" rel="noopener">Original URL</a>':'')+(v.video?'<a href="'+esc(v.video)+'" download>Download</a>':'')+'</div></div>').join('')+'</div></article>').join('')||'<p>No items.</p>';$('#count').textContent=list.length+' items';$('#page').textContent=(page+1)+' / '+Math.max(1,Math.ceil(list.length/size));$('#prev').disabled=page===0;$('#next').disabled=(page+1)*size>=list.length;
 $('#items').querySelectorAll('video').forEach(v=>{v.addEventListener('play',()=>document.querySelectorAll('video').forEach(o=>{if(o!==v)o.pause()}));v.addEventListener('error',()=>{let e=document.createElement('p');e.className='error';e.textContent='Playback unavailable. Open Original URL.';v.after(e)})});}
$('#items').addEventListener('click',e=>{let b=e.target.closest('[data-verdict]');if(!b)return;let id=b.closest('[data-id]').dataset.id;state.answers[id]=state.answers[id]===b.dataset.verdict?'-':b.dataset.verdict;save();b.parentElement.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',verdict(id)===x.dataset.verdict))});
$('#items').addEventListener('input',e=>{if(!e.target.dataset.note)return;let id=e.target.dataset.note;state.notes[id]=e.target.value;e.target.classList.toggle('has-note',!!e.target.value.trim());save();e.target.previousElementSibling.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',verdict(id)===x.dataset.verdict))});
for(let f of ['brand','batch'])$('#'+f).onchange=()=>{page=0;render()};$('#prev').onclick=()=>{page--;render();window.scrollTo(0,0)};$('#next').onclick=()=>{page++;render();window.scrollTo(0,0)};
for(let f of ['overall','name'])$('#'+f).oninput=e=>{state[f]=e.target.value;save()};
$('#copy').onclick=async()=>{let text=[CONFIG.title,state.name,...ids.map(id=>id+': '+verdict(id)+(state.notes[id]?' | '+state.notes[id]:'')),'Overall: '+state.overall,location.href].join('\n');try{await navigator.clipboard.writeText(text);$('#status').textContent='Copied.'}catch(e){$('#copy-fallback').hidden=false;$('#copy-fallback').value=text;$('#copy-fallback').select();$('#status').textContent='Select and copy the answers below.'}};
$('#send').onclick=async()=>{let b=$('#send');b.disabled=true;$('#status').textContent='Sending…';try{if(!CONFIG.store)throw Error('Store is not configured. Use Copy answers.');let r=await fetch(CONFIG.store+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Cannot read answer store. Your answers remain saved here.');let d=await r.json();if(!Array.isArray(d.submissions))throw Error('Answer store unavailable.');let name=state.name.trim()||'Anonymous';let rec={name,ts:new Date().toISOString(),answers:encode(),ids,notes:state.notes,overall:state.overall};d.submissions=d.submissions.filter(s=>(s.name||'').trim().toLowerCase()!==name.toLowerCase());d.submissions.push(rec);r=await fetch(CONFIG.store,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!r.ok)throw Error('Send failed. Please retry or copy your answers.');$('#status').textContent='Answers sent.'}catch(e){$('#status').textContent=e.message}finally{b.disabled=false}};
fetch('manifest.json?v=20260912',{cache:'no-store'}).then(r=>r.json()).then(d=>{items=d.items;ids=items.flatMap(i=>i.variants.filter(v=>!v.reference).map(v=>v.id));key='paulqc:'+CONFIG.id;try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch(e){}let h=location.hash.match(/^#r=([KFX-]+)$/);if(h&&(h[1].length===ids.length||h[1].length===100))ids.slice(0,h[1].length).forEach((id,n)=>state.answers[id]=h[1][n]);if(new URLSearchParams(location.search).get('batch')==='new')$('#batch').value='new';$('#title').textContent=CONFIG.title;document.title=CONFIG.title;$('#brand').insertAdjacentHTML('beforeend',[...new Set(items.map(i=>i.brand).filter(Boolean))].sort().map(b=>'<option>'+esc(b)+'</option>').join(''));$('#overall').value=state.overall;$('#name').value=state.name;render();save()}).catch(()=>$('#items').textContent='The review could not load. Please refresh.');
