'use strict';
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const RATING={E:'Excellent',V:'Very good',G:'Good'},SCORE={E:3,V:2,G:1},ATTACHMENTS='https://github.com/frompaulxam-gif/venture-reels-paulqc/releases/download/video-downloads-v1/';
let items=[],ids=[],list=[],state={answers:{},notes:{},ratings:{},overall:'',name:'',positions:{}},key='',current=0,observer,sound=false,restoring=false;
function verdict(id){const v=state.answers[id]||'-';return(state.notes[id]||'').trim()&&v!=='X'?'F':v}
function encode(){return ids.map(verdict).join('')}
function ratingCode(){return ids.map(id=>RATING[state.ratings[id]]?state.ratings[id]:'-').join('')}
function save(){try{localStorage.setItem(key,JSON.stringify(state));const u=new URL(location.href);u.hash='r='+encode()+(Object.keys(state.ratings).length?'&q='+ratingCode():'');history.replaceState(null,'',u)}catch(e){$('#status').textContent='Browser saving unavailable. Use Copy answers.'}}
function selected(){let selected=items.filter(i=>(!$('#brand').value||i.brand===$('#brand').value)&&(!$('#batch').value||($('#batch').value==='original'?!i.batch:i.batch==='2026-09-12'))&&(!$('#rating-filter').value||($('#rating-filter').value==='-'?!state.ratings[i.variants[0].id]:state.ratings[i.variants[0].id]===$('#rating-filter').value)));if($('#order').value==='rating')selected.sort((a,b)=>(SCORE[state.ratings[b.variants[0].id]]||0)-(SCORE[state.ratings[a.variants[0].id]]||0));return selected}
function positionKey(){return[$('#batch').value,$('#brand').value,$('#rating-filter').value,$('#order').value].join('|')}
function media(v){if(v.video)return '<video controls playsinline loop muted preload="none" poster="'+esc(v.poster||'')+'" data-src="'+esc(v.video)+'" aria-label="Reel '+esc(v.id)+'"></video>';if(v.image)return '<a href="'+esc(v.image)+'" target="_blank" rel="noopener"><img src="'+esc(v.image)+'" loading="lazy" alt="'+esc(v.label||v.id)+'"></a>';return '<div class="empty">Video unavailable<br><a target="_blank" rel="noopener" href="'+esc(v.source)+'">Open original Reel</a></div>'}
function card(i,n){const v=i.variants[0],id=v.id;return '<article class="reel-card" data-code="'+esc(i.code)+'" data-index="'+n+'" aria-label="'+esc(i.code+' '+i.brand)+'"><div class="reel-stage">'+media(v)+(v.video?'<div class="stage-tools"><button data-sound aria-label="Toggle sound">'+(sound?'Sound on':'Sound off')+'</button><button data-fullscreen aria-label="Full screen '+esc(i.code)+'">Full screen</button></div>':'')+'</div><div class="reel-panel"><div class="reel-meta"><strong>'+esc(i.code)+'</strong><span>'+esc(i.brand||'')+'</span></div>'+(v.reference?'':'<div class="rating-controls" data-id="'+esc(id)+'" role="group" aria-label="Rating for '+esc(i.code)+'">'+Object.entries(RATING).map(([k,t])=>'<button data-rating="'+k+'" aria-pressed="'+(state.ratings[id]===k)+'">'+t+'</button>').join('')+'</div><div class="controls" data-id="'+esc(id)+'" role="group" aria-label="Verdict for '+esc(i.code)+'">'+[['K','Keep'],['F','Flag'],['X','Kill']].map(([k,t])=>'<button data-verdict="'+k+'" aria-pressed="'+(verdict(id)===k)+'">'+t+'</button>').join('')+'</div><details class="reel-notes '+((state.notes[id]||'').trim()?'has-note':'')+'"><summary>Notes'+((state.notes[id]||'').trim()?' •':'')+'</summary><textarea data-note="'+esc(id)+'" aria-label="Notes for '+esc(i.code)+'">'+esc(state.notes[id]||'')+'</textarea></details>')+'<div class="reel-links">'+(v.video?'<a class="download-link" href="'+esc(ATTACHMENTS+v.video.split('/').pop())+'" target="_blank" rel="noopener" download="'+esc(i.code)+'.mp4">Download MP4</a>':'')+'<a class="original-link" href="'+esc(v.source)+'" target="_blank" rel="noopener">Original URL</a></div>'+(v.video?'<details class="download-options"><summary>Download options</summary><button data-save-file="'+esc(v.video)+'" data-filename="'+esc(i.code)+'.mp4">Save backup MP4</button><div class="reel-links"><a href="'+esc(v.video)+'" target="_blank" rel="noopener">Open video file</a><button data-copy-url="'+esc(ATTACHMENTS+v.video.split('/').pop())+'">Copy download link</button></div><p class="download-state" role="status"></p></details>':'')+'</div></article>'}
function updatePosition(){const count=list.length;$('#page').textContent=count?(current+1)+' / '+count:'0 / 0';$('#prev').disabled=current<=0;$('#next').disabled=current>=count-1;$('#count').textContent=count+' videos'}
function activate(n){current=n;updatePosition();const cards=[...$('#items').querySelectorAll('.reel-card')];cards.forEach((c,j)=>{c.inert=j!==n;const v=c.querySelector('video');if(!v)return;if(j===n){if(!v.getAttribute('src'))v.src=v.dataset.src;v.muted=!sound;v.play().catch(()=>{})}else v.pause()});if(list[n]&&!restoring){state.positions[positionKey()]=list[n].code;save()}}
function jump(n,behavior='smooth'){const cards=$('#items').querySelectorAll('.reel-card');n=Math.max(0,Math.min(n,cards.length-1));if(cards[n])$('#items').scrollTo({top:cards[n].offsetTop-$('#items').offsetTop,behavior})}
function render(){if(observer)observer.disconnect();$('#items').querySelectorAll('video').forEach(v=>v.pause());list=selected();$('#items').innerHTML=list.map(card).join('')||'<p class="empty-feed">No matching videos.</p>';const saved=state.positions[positionKey()];current=Math.max(0,list.findIndex(i=>i.code===saved));restoring=true;updatePosition();observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting&&e.intersectionRatio>.6).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)activate(Number(visible.target.dataset.index))},{root:$('#items'),threshold:[.6,.85]});$('#items').querySelectorAll('.reel-card').forEach(c=>observer.observe(c));$('#items').querySelectorAll('video').forEach(v=>v.addEventListener('error',()=>{const p=v.closest('.reel-card').querySelector('.download-state');if(p)p.textContent='Playback unavailable. Use Download MP4 or Original URL.'}));requestAnimationFrame(()=>{jump(current,'instant');restoring=false;activate(current)})}
function refreshChoices(card,id){card.querySelectorAll('[data-verdict]').forEach(b=>b.setAttribute('aria-pressed',verdict(id)===b.dataset.verdict));card.querySelectorAll('[data-rating]').forEach(b=>b.setAttribute('aria-pressed',state.ratings[id]===b.dataset.rating))}
$('#items').addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;const c=b.closest('.reel-card');if(b.dataset.verdict||b.dataset.rating){const id=b.parentElement.dataset.id;if(b.dataset.verdict)state.answers[id]=state.answers[id]===b.dataset.verdict?'-':b.dataset.verdict;else{if(state.ratings[id]===b.dataset.rating)delete state.ratings[id];else state.ratings[id]=b.dataset.rating}save();refreshChoices(c,id);if(b.dataset.rating&&($('#rating-filter').value||$('#order').value==='rating'))render();return}if(b.hasAttribute('data-sound')){sound=!sound;$('#items').querySelectorAll('[data-sound]').forEach(x=>x.textContent=sound?'Sound on':'Sound off');const v=c.querySelector('video');v.muted=!sound;v.play().catch(()=>{});return}if(b.hasAttribute('data-fullscreen')){try{if(document.fullscreenElement)await document.exitFullscreen();else if(c.requestFullscreen)await c.requestFullscreen();else c.querySelector('video')?.webkitEnterFullscreen?.()}catch(e){}return}if(b.dataset.copyUrl){try{await navigator.clipboard.writeText(b.dataset.copyUrl);c.querySelector('.download-state').textContent='Download link copied.'}catch(e){c.querySelector('.download-state').textContent=b.dataset.copyUrl}return}if(b.dataset.saveFile){const status=c.querySelector('.download-state');b.disabled=true;status.textContent='Preparing video…';try{const r=await fetch(b.dataset.saveFile);if(!r.ok)throw Error();const blob=await r.blob();if(!blob.type.includes('video'))throw Error();const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=b.dataset.filename;a.textContent='Save prepared MP4';status.replaceChildren(a);a.click();setTimeout(()=>URL.revokeObjectURL(url),300000)}catch(e){status.textContent='Use Download MP4, or open the video file in your browser and save it.'}finally{b.disabled=false}}});
$('#items').addEventListener('input',e=>{const id=e.target.dataset.note;if(!id)return;state.notes[id]=e.target.value;const details=e.target.closest('details');details.classList.toggle('has-note',!!e.target.value.trim());details.querySelector('summary').textContent='Notes'+(e.target.value.trim()?' •':'');save();refreshChoices(e.target.closest('.reel-card'),id)});
for(const f of ['batch','brand','rating-filter','order'])$('#'+f).onchange=()=>{const u=new URL(location.href);if($('#batch').value)u.searchParams.set('batch',$('#batch').value);else u.searchParams.delete('batch');history.replaceState(null,'',u);render()};
$('#prev').onclick=()=>jump(current-1);$('#next').onclick=()=>jump(current+1);window.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT|VIDEO/.test(e.target.tagName)||document.querySelector('dialog[open]'))return;if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();jump(current+(e.key==='ArrowDown'?1:-1))}});
function openDialog(id){$('#items').querySelectorAll('video').forEach(v=>v.pause());$(id).showModal()}$('#filters').onclick=()=>openDialog('#filter-dialog');$('#answers').onclick=()=>openDialog('#answer-dialog');document.querySelectorAll('dialog').forEach(d=>d.addEventListener('close',()=>activate(current)));document.addEventListener('visibilitychange',()=>{if(document.hidden)$('#items').querySelectorAll('video').forEach(v=>v.pause())});document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());for(const f of ['overall','name'])$('#'+f).oninput=e=>{state[f]=e.target.value;save()};
$('#copy').onclick=async()=>{const text=[CONFIG.title,state.name,...ids.map(id=>id+': '+verdict(id)+(state.ratings[id]?' | '+RATING[state.ratings[id]]:'')+(state.notes[id]?' | '+state.notes[id]:'')),'Overall: '+state.overall,location.href].join('\n');try{await navigator.clipboard.writeText(text);$('#status').textContent='Copied.'}catch(e){$('#copy-fallback').hidden=false;$('#copy-fallback').value=text;$('#copy-fallback').select();$('#status').textContent='Select and copy the answers below.'}};
$('#send').onclick=async()=>{const b=$('#send');b.disabled=true;$('#status').textContent='Sending…';try{const r=await fetch(CONFIG.store+'?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('Cannot read answer store. Your answers remain saved here.');const d=await r.json();if(!Array.isArray(d.submissions))throw Error('Answer store unavailable.');const name=state.name.trim()||'Anonymous',rec={name,ts:new Date().toISOString(),answers:encode(),ids,notes:state.notes,ratings:state.ratings,overall:state.overall};d.submissions=d.submissions.filter(s=>(s.name||'').trim().toLowerCase()!==name.toLowerCase());d.submissions.push(rec);const sent=await fetch(CONFIG.store,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});if(!sent.ok)throw Error('Send failed. Retry or copy your answers.');$('#status').textContent='Answers sent.'}catch(e){$('#status').textContent=e.message}finally{b.disabled=false}};
fetch('manifest.json?v=reels1',{cache:'no-store'}).then(r=>r.json()).then(d=>{items=d.items;ids=items.flatMap(i=>i.variants.filter(v=>!v.reference).map(v=>v.id));key='paulqc:'+CONFIG.id;try{state={...state,...JSON.parse(localStorage.getItem(key)||'{}')}}catch(e){}for(const f of ['answers','notes','ratings','positions'])if(!state[f]||typeof state[f]!=='object')state[f]={};const h=new URLSearchParams(location.hash.slice(1)),r=h.get('r'),q=h.get('q');if(r&&/^[KFX-]+$/.test(r)&&[100,ids.length].includes(r.length))ids.slice(0,r.length).forEach((id,n)=>{if(r[n]!==verdict(id))state.answers[id]=r[n]});if(q&&/^[EVG-]+$/.test(q)&&q.length===ids.length)ids.forEach((id,n)=>{if(q[n]==='-')delete state.ratings[id];else state.ratings[id]=q[n]});const batch=new URLSearchParams(location.search).get('batch');if(['new','original'].includes(batch))$('#batch').value=batch;$('#brand').insertAdjacentHTML('beforeend',[...new Set(items.map(i=>i.brand).filter(Boolean))].sort().map(b=>'<option>'+esc(b)+'</option>').join(''));$('#overall').value=state.overall;$('#name').value=state.name;render();save()}).catch(()=>$('#items').innerHTML='<p class="empty-feed">The review could not load. Please refresh.</p>');
